In [1]:
import numpy as np
a = np.array([1, 2, 3]) # Create a rank 1 array
print("One dimensional array a = ",a)
b = np.array([[1,2,3],[4,5,6]])
print("Two dimensional array b = ",b)
print("Size of the array: ",a.shape)
print("Element at indices 0,1,2: ",a[0], a[1], a[2])
a[0] = 5 # Change an element of the array
print("Array after changing the element at index 0: ",a)
a = np.zeros((2,2)) # Create an array of all zeros
print("An array of all zeros: ",a)
b = np.ones((1,2)) # Create an array of all ones
print("An array of all ones: ",b)
c = np.full((2,2), 7) # Create a constant array
print("A constant array: ",c)
d = np.eye(2) # Create a 2x2 identity matrix
print("A 2*2 identity matrix : ",d)
e = np.random.random((2,2)) # Create an array filled with random values
print("An array with random values: ",e)

One dimensional array a =  [1 2 3]
Two dimensional array b =  [[1 2 3]
 [4 5 6]]
Size of the array:  (3,)
Element at indices 0,1,2:  1 2 3
Array after changing the element at index 0:  [5 2 3]
An array of all zeros:  [[0. 0.]
 [0. 0.]]
An array of all ones:  [[1. 1.]]
A constant array:  [[7 7]
 [7 7]]
A 2*2 identity matrix :  [[1. 0.]
 [0. 1.]]
An array with random values:  [[0.16117147 0.73371363]
 [0.09931737 0.54970403]]


In [2]:
import numpy as np
print("Array indexing: slicing")
al = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("al = ",al)
b=al[:2, 1:3]
print("Subarray consisting of first two rows and columns 1 and 2: ",b)
b=al[1:2,:]
print("Subarray consists of second row: ",b)
print("Accessing columns: ")
b=al[:,1]
print(b,b.shape)
c=al[:1:2]
print(c,c.shape)
print("Array integer indexing: ")
a2 = np.array([[1,2], [3, 4], [5, 6]])
print("a2 = ",a2)
print("Example of array integer indexing: ",a2[[0, 1, 2], [0, 1, 0]])
# When using integer array indexing, you can reuse the same element from the source #array
print("a2[[0, 0], [1, 1]]D")
#Equivalent to the previous integer array indexing example
print(np.array([a2[0, 1], a[0, 1]]))
a3 = a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print("a3 = ",a3)
# Create an array of indices
b = np.array([0, 2, 0, 1])
print("b = ",b)
# Select one element from each row of a using the indices in b
print("a3",a3[np.arange(4), b])
# Mutate one element from each row of a using the indices in b
a3 [np.arange(4), b]+= 10
print("a3 = ",a3)
print("Boolean array indexing: ")
a = np.array([[1,2], [3, 4], [5, 6]])
print("a = ",a)
bool_idx= (a>2)
print("Elements greater than 2: ",a[bool_idx])

Array indexing: slicing
al =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Subarray consisting of first two rows and columns 1 and 2:  [[2 3]
 [6 7]]
Subarray consists of second row:  [[5 6 7 8]]
Accessing columns: 
[ 2  6 10] (3,)
[[1 2 3 4]] (1, 4)
Array integer indexing: 
a2 =  [[1 2]
 [3 4]
 [5 6]]
Example of array integer indexing:  [1 4 5]
a2[[0, 0], [1, 1]]D
[2. 0.]
a3 =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b =  [0 2 0 1]
a3 [ 1  6  7 11]
a3 =  [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
Boolean array indexing: 
a =  [[1 2]
 [3 4]
 [5 6]]
Elements greater than 2:  [3 4 5 6]


In [3]:
import numpy as n
x = np.array([[1,2], [3, 4]], dtype=np.float64)
y = np.array([[6,9], [4, 4]], dtype=np.float64)
print("x = ",x)
print("y=",y)
print("Element wise addition: ",np.add(x, x))
print("Element wise subtraction: ",np.subtract(x, y))
print("Element wise multiplication: ",np.multiply(x, y))
print("Element wise square root of x: ",np.sqrt(x))
print("Matrix multiplication: ",np.dot(x, y))
print("Sum of all elements of matrix x: ",np.sum(x))
print("Sum of elements in each column of matrix y: ",np.sum(y,axis=0))
print("Sum of elements in each row of matrix y: ",np.sum(y,axis=1)) 
print("Transpose of matrix x: ",x.T)

x =  [[1. 2.]
 [3. 4.]]
y= [[6. 9.]
 [4. 4.]]
Element wise addition:  [[2. 4.]
 [6. 8.]]
Element wise subtraction:  [[-5. -7.]
 [-1.  0.]]
Element wise multiplication:  [[ 6. 18.]
 [12. 16.]]
Element wise square root of x:  [[1.         1.41421356]
 [1.73205081 2.        ]]
Matrix multiplication:  [[14. 17.]
 [34. 43.]]
Sum of all elements of matrix x:  10.0
Sum of elements in each column of matrix y:  [10. 13.]
Sum of elements in each row of matrix y:  [15.  8.]
Transpose of matrix x:  [[1. 3.]
 [2. 4.]]


In [4]:
import numpy as np
print("Example for broadcasting: ")
v=np.array([1,2,3])
w=np.array([4,5])
print("v = ",v)
print("w = ",w)
print("Outer product of above vectors: ")
print(np.reshape(v,(3,1))*w)
x=np.array([[1,2,3],[4,5,6]])
print("x = ",x)
print("Resultant matrix after adding the vector x to each row of matrix v: ")
print(x+v)
print("Example for broadcasting fails: ")
print("Adding the vector x to each column of matrix w will generate an error") 
print("Solution: Reshape the matrix w then the result will be: ")
print(x+np.reshape(w, (2,1)))

Example for broadcasting: 
v =  [1 2 3]
w =  [4 5]
Outer product of above vectors: 
[[ 4  5]
 [ 8 10]
 [12 15]]
x =  [[1 2 3]
 [4 5 6]]
Resultant matrix after adding the vector x to each row of matrix v: 
[[2 4 6]
 [5 7 9]]
Example for broadcasting fails: 
Adding the vector x to each column of matrix w will generate an error
Solution: Reshape the matrix w then the result will be: 
[[ 5  6  7]
 [ 9 10 11]]
